
exports.seed = knex => {

      // Inserts seed entries
      return knex('movies').insert([
        {id: 1, title: 'Varsity Blues', director: 'Brian Robbins', year: 1999, rating: 5, posterURL: 'https://images-na.ssl-images-amazon.com/images/M/MV5BZGVlYjRmYTUtNTRiYS00ODNmLThlNDQtNzc3OWJmYTlkMzM0L2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg', trailerEmbed: 'vi3144725529', storyline: `In small-town Texas, high school football is a religion. The head coach is deified, as long as the team is winning and 17-year-old schoolboys carry the hopes of an entire community onto the gridiron every Friday night. In his 35th year as head coach, Bud Kilmer (Jon Voight) is trying to lead his West Canaan Coyotes to their 23rd division title. When star quarterback Lance Harbor (Paul Walker) suffers an injury, the Coyotes are forced to regroup under the questionable leadership of John Moxon (James Van Der Beek), a second-string quarterback with a slightly irreverent approach to the game. "Varsity Blues" explores our obsession with sports and how teenage athletes respond to the extraordinary pressures places on them.`},
        {id: 2, title: 'The Fast and the Furious', director: 'Rob Cohen & Mel City', year: 2001, rating: 5, posterURL: 'https://images-na.ssl-images-amazon.com/images/M/MV5BNzlkNzVjMDMtOTdhZC00MGE1LTkxODctMzFmMjkwZmMxZjFhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY1000_CR0,0,672,1000_AL_.jpg', trailerEmbed: 'vi2508980505', storyline: `Los Angeles street racer Dominic Toretto falls under the suspicion of the LAPD as a string of high-speed electronics truck robberies rocks the area. Brian O'Connor, an officer of the LAPD, joins the ranks of Toretto's highly skilled racing crew undercover to convict Toretto. However, O'Connor finds himself both enamored with this new world and in love with Toretto's sister, Mia. As a rival racing crew gains strength, O'Connor must decide where his loyalty really lies.`},
        {id: 3, title: 'The Skulls', director: 'Rob Cohen', year: 2000, rating: 5, posterURL: 'https://images-na.ssl-images-amazon.com/images/M/MV5BODA2OTQ0NzctZTYwNi00N2E2LWJhN2UtOTc4N2UzYWRiOWVjL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg', trailerEmbed: 'vi2381971737', storyline: `Luke McNamara, a college senior from a working class background joins a secret elitist college fraternity organization called "The Skulls", in hope of gaining acceptance into Harvard Law School. At first seduced by the club's trapping of power and wealth, a series of disturbing incidents, such as his best friends suicide, leads Luke to investigate the true nature of the organization and the truth behind his friends supposed suicide. He starts realizing that his future and possibly his life is in danger.`},
        {id: 4, title: `She's All That`, director: 'Robert Iscove', year: 1999, rating: 5, posterURL: 'https://images-na.ssl-images-amazon.com/images/M/MV5BY2Y0N2YyOTQtMGNiYy00ZDViLTgxYmItODkxNzlkMWVjNTFkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg', trailerEmbed: 'vi600874521', storyline: `Luke McNamara, a college senior from a working class background joins a secret elitist college fraternity organization called "The Skulls", in hope of gaining acceptance into Harvard Law School. At first seduced by the club's trapping of power and wealth, a series of disturbing incidents, such as his best friends suicide, leads Luke to investigate the true nature of the organization and the truth behind his friends supposed suicide. He starts realizing that his future and possibly his life is in danger.`},
        {id: 5, title: 'Pleasantville', director: 'Gary Ross', year: 1998, rating: 5, posterURL: 'https://images-na.ssl-images-amazon.com/images/M/MV5BYTRlYzk4NDktODE3Ni00YjFkLWFjYmUtNjg1MzdmYmFmOTJkXkEyXkFqcGdeQXVyMTAwMzUyOTc@._V1_.jpg', trailerEmbed: 'vi2979791129', storyline: `David Wagner is a kid whose mind is stuck in the 1950s. He's addicted to a classic 50's sitcom television show called "Pleasantville". Pleasntville is a simple place, a place where all of its citizens are swell and simple-minded folks, a place where the word "violence", and life outside of Pleasantville, is unbeknown to its inhabitants; things are perfect down in Pleasantville. One evening, the life of David and his obnoxious sister Jennifer take a bizarre turn when an eccentric repairman hand them a supposed magical remote. After a quarrel between the siblings, they inexplicably zap themselves into the world of "Pleasantville". Now, David and Jennifer must adjust to a 50s lifestyle of repressed desires and considerably different societal values while trying to find their way home.`}
      ]).then(() => {
    return knex.raw(
      `SELECT setval('movies_id_seq', (SELECT MAX(id) FROM movies));`
    );
  })
};
